# Generated by Django 2.0.2 on 2019-10-10 15:54

import center.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=center.models.generate_access_token, max_length=64, verbose_name='通行秘钥')),
                ('concurrency', models.IntegerField(verbose_name='并发数')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('expiration_time', models.DateTimeField(verbose_name='到期时间')),
                ('renewal_time', models.DateTimeField(blank=True, null=True, verbose_name='续费时间')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('transaction_type', models.SmallIntegerField(choices=[(1, '充值'), (2, '新购'), (3, '续费')], verbose_name='交易类型')),
                ('amount', models.FloatField(verbose_name='订单金额')),
                ('pay_channel', models.SmallIntegerField(blank=True, choices=[(1, '钱包'), (2, '支付宝'), (3, '微信')], null=True, verbose_name='支付渠道')),
                ('pay_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已完成'), (3, '超时未支付'), (4, '已取消')], default=1, verbose_name='订单状态')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=1, verbose_name='周期')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('additional_concurrency', models.IntegerField(default=0, verbose_name='额外并发数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Order', verbose_name='订单')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品名称')),
                ('doc_url', models.URLField(blank=True, null=True, verbose_name='接口文档链接地址')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否开放')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.SmallIntegerField(choices=[(1, '时'), (2, '日'), (3, '周'), (4, '月'), (5, '季'), (6, '年')], verbose_name='套餐期限')),
                ('price', models.FloatField(verbose_name='套餐价格')),
                ('default_concurrency', models.IntegerField(default=5, verbose_name='默认并发数')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.Product', verbose_name='产品')),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.ProductPackage', verbose_name='产品套餐包'),
        ),
    ]
