# Generated by Django 2.0.2 on 2019-10-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20191015_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacechannel',
            name='product_package',
        ),
        migrations.AddField(
            model_name='interfacechannel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='center.Product', verbose_name='产品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(1, '充值'), (2, '新购'), (3, '续费'), (4, '升级')], verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.ProductPackage', verbose_name='产品套餐包'),
        ),
    ]
