# Generated by Django 2.0.2 on 2019-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20191010_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='additional_concurrency_price',
            field=models.FloatField(verbose_name='额外并发单价'),
        ),
    ]
