# Generated by Django 2.0.2 on 2019-10-11 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20191010_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下单时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付宝交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_channel',
            field=models.SmallIntegerField(choices=[(1, '钱包'), (2, '支付宝'), (3, '微信')], default=2, verbose_name='支付渠道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
    ]
