# Generated by Django 2.0.2 on 2020-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_channel',
            field=models.SmallIntegerField(blank=True, choices=[(1, '钱包'), (2, '支付宝'), (3, '微信')], null=True, verbose_name='支付渠道'),
        ),
    ]
