# Generated by Django 2.0.2 on 2020-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_ordergoods_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='renewal_time',
            field=models.DateTimeField(verbose_name='续费时间'),
        ),
    ]
