# Generated by Django 2.0.2 on 2020-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20200304_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='renewal_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='续费时间'),
        ),
    ]
